spring:
  application:
    name: order
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: shopping
    password: asd123
    url: jdbc:mariadb://localhost:3306/shopping
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
